---
- name: Jupyter Lab | Pull docker image {{ nest_simulator_image }}
  shell: "docker pull {{ nest_simulator_image }}"

- name: Jupyter Lab | Create systemd unit file
  template:
    src: jupyter-lab.service.j2
    dest: /etc/systemd/system/jupyter-lab.service
    mode: 644

- name: Jupyter Lab | Activate jupyter-lab.service on boot
  systemd:
    name: jupyter-lab
    enabled: yes
    daemon-reload: yes
